spring:
  application:
    name: ecom-order-service
server:
  port: 8080

logging:
  level:
    org.example.ecomorderservice.client: DEBUG
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

resilience4j:
  ratelimiter:
    instances:
      inventoryService:
        limit-for-period: 2
        limit-refresh-period: 10s
        timeout-duration: 0s
